steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: ['-c', 'git submodule update --init --recursive']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-fastapi', 'Backend']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend-fastapi']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      SERVICE="${_SERVICE:-backend-fastapi}"
      REGION="${_REGION:-us-central1}"
      ALLOW="${_ALLOW:--allow-unauthenticated}"
      echo "Deploying to Cloud Run: service=$SERVICE region=$REGION allow_auth=$ALLOW"
      gcloud run deploy "$SERVICE" --image="gcr.io/$PROJECT_ID/backend-fastapi" --region="$REGION" --platform=managed $ALLOW

images:
- 'gcr.io/$PROJECT_ID/backend-fastapi'

substitutions:
  _SERVICE: 'backend-fastapi'
  _REGION: 'us-central1'
  _ALLOW: '--allow-unauthenticated'
timeout: '1200s'
